friend_group/src/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete,
)


urlpatterns = [
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')
    
]

friend_group/src/aptfrnd/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from aptfrnd import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friend_group/src/home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views
from .views import users_list, leaderboard, friend_request, notification, resolve_request, change_group_name

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends'),
    url(r'^searchusers/$', users_list, name='list'),
    url(r'^leaderboard/$', leaderboard, name='leaderboard'),
    url(r'^request/(?P<pk>\d+)/$', friend_request, name='send_request'),
    url(r'^resolverequest/(?P<operation>.+)/(?P<pk>\d+)/$', resolve_request, name='resolve_request'),
    url(r'^notification/$', notification, name='notification'),
    url(r'^change_group_name/$', change_group_name, name='change_group_name'),
]

friend_group/src/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

#class UserProfileManager(models.Manager):
 #   def get_queryset(self):
  #      return super(UserProfileManager, self).get_queryset().filter(city='Delhi')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=200, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)
    coin = models.IntegerField(default='500')
    rank = models.IntegerField(default='0')
    notification = models.CharField(max_length=400, default="" )

    #India = UserProfileManager()

    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'

    def __str__(self):
        return self.user.username

#def create_profile(sender, **kwargs):
 #   if kwargs['created']:
  #      user_profile = UserProfile.objects.create(user=kwargs['instance'])

#post_save.connect(create_profile, sender=User)

friend_group/src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )
        

class EditPersonalDetailsForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = (
            'description',
            'phone',
            'city',
            'website'
        )
        

friend_group/src/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
    EditPersonalDetailsForm
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from urllib import quote_plus
from home.models import Friend, FriendRequest
from .models import UserProfile


def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # friend_cls_obj = Friend.objects.create(current_user=user)
            #userpro = UserProfile.objects.create(user=user)
            #friend_cls_obj.friends.add(userpro)
            # FriendRequest.objects.create(receiver=user)
            return redirect(reverse('accounts:login'))
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

def view_profile(request, pk=None):
    if pk:
        user = UserProfile.objects.get(pk=pk)
    else:
        user = request.user.userprofile
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        form1 = EditPersonalDetailsForm(request.POST or None, request.FILES or None, instance=request.user.userprofile)
        ds = request.POST['description']
        ct = request.POST['city']
        ws = request.POST['website']
        ph = request.POST['phone']
        print(ds, ph, ct, ws)
        if form.is_valid() and form1.is_valid():
            form.save()
            if request.POST['image'] is not '':
                request.user.userprofile.image = "profile_image/"+request.POST['image']
                print("bb",request.POST['image'])
                request.user.userprofile.save()
            else:
                print("aa",request.user.userprofile.image.url)
            form1.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        form1 = EditPersonalDetailsForm(instance=request.user.userprofile)
        args = {'form': form, 'form1': form1,}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

friend_group/src/accounts/templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		{% load static %}
		<script src="{% static 'js/annyang.min.js' %}"></script>
		<script src="{% static 'js/voice.js' %}"></script>
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:home' %}">Aptence Group(Home)</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.user.is_authenticated or user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                    <li><a href="{% url 'home:list' %}">Search Friend</a></li>
                    <li><a href="{% url 'home:leaderboard' %}">Leaderboard</a></li>
                    <li><a href="{% url 'home:notification' %}">Notification</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:view_profile' %}">{% if request.user %} Hello, {{ user.get_full_name}}{{ user.user.get_full_name }}{% endif %}</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif %}
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
        {% block body %}
            <h1>Base</h1>
        {% endblock %}
         {% block content %}
          
        {% endblock %}
    </body>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>