friend_group/src/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete,
)


urlpatterns = [
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')
    
]

friend_group/src/aptfrnd/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from aptfrnd import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friend_group/src/home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views
from .views import users_list, leaderboard, friend_request, notification, resolve_request, change_group_name

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends'),
    url(r'^searchusers/$', users_list, name='list'),
    url(r'^leaderboard/$', leaderboard, name='leaderboard'),
    url(r'^request/(?P<pk>\d+)/$', friend_request, name='send_request'),
    url(r'^resolverequest/(?P<operation>.+)/(?P<pk>\d+)/$', resolve_request, name='resolve_request'),
    url(r'^notification/$', notification, name='notification'),
    url(r'^change_group_name/$', change_group_name, name='change_group_name'),
]

friend_group/src/home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from accounts.models import UserProfile

class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username + " : " + self.post


class Friend(models.Model):
    friends = models.ManyToManyField(UserProfile) 
    current_user = models.ForeignKey(User, related_name='owner', null=True)
    rank = models.IntegerField(default='0')
    group_name = models.CharField(max_length=20, default="Group", help_text="Group name must not be greater than 20 characters")


    def make_friend(self, new_friend):
        self.friends.add(new_friend)

    def lose_friend(self, friend_to_be_removed):
        self.friends.remove(friend_to_be_removed)

    def __str__(self):
        return self.current_user.username


class FriendRequest(models.Model):
    sender = models.ManyToManyField(UserProfile) 
    receiver = models.ForeignKey(User, related_name='receiver', null=True)
    notification = models.CharField(max_length=300)

    def __str__(self):
        return self.receiver.username

def initializer_friends_related_objects(sender, instance, **kwargs):

    if kwargs.get('created'):
        friend_cls_obj = Friend.objects.create(current_user=instance)
        userpro = UserProfile.objects.create(user=instance)
        friend_cls_obj.friends.add(userpro)
        FriendRequest.objects.create(receiver=instance)

models.signals.post_save.connect(initializer_friends_related_objects, sender=User)

friend_group/src/home/forms.py
from django import forms
from home.models import Post


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))

    class Meta:
        model = Post
        fields = ('post',)

friend_group/src/home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from home.forms import HomeForm
from home.models import Post, Friend, FriendRequest
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from urllib import quote_plus
from utils import Rank
from accounts.models import UserProfile


class HomeView(TemplateView):
    template_name = 'home.html'

    def get(self, request):
        rank_obj = Rank(request.user)
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        users = UserProfile.objects.exclude(user=request.user.id)
        user = Friend.objects.get(current_user=request.user)
        friend = user.friends.exclude(user=request.user.id)
        paginator = Paginator(posts, 10) # Show 10 records per page
        page_request_var = "page"
        page = request.GET.get(page_request_var)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)

        args = {
            'form': form, 'posts': posts, 'users': users, 'friends': friend, 'frndobj': user, 'rank_obj': rank_obj.rank(),
            'page_request_var' : page_request_var,
        }
        return render(request, self.template_name, args)

    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            text = form.cleaned_data['post']
            form = HomeForm()
            return redirect('home:home')

        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)

    

def change_friends(request, operation, pk):
    friend = UserProfile.objects.get(pk=pk)
    currentuser = UserProfile.objects.get(user=request.user)
    friend_cls_obj = Friend.objects.get(current_user=request.user)
    opposite_friend = Friend.objects.get(current_user=friend.user)
    if operation == 'add':
        friend_cls_obj.make_friend(friend)
    elif operation == 'remove':
        friend_cls_obj.lose_friend(friend)
        opposite_friend.lose_friend(currentuser)
    return redirect('home:home')

def users_list(request):
        #today = timezone.now()
        queryset_list = UserProfile.objects.exclude(user=request.user.id) #filter(draft=False).filter(publish__lte=timezone.now()) #.all() #.order_by("-timestamp")
        user = Friend.objects.get(current_user=request.user)
        print user
        friend = user.friends.exclude(user=request.user.id)
        print friend
        cur_user = UserProfile.objects.get(user=request.user)
        current_user_sent_request = FriendRequest.objects.filter(sender=cur_user).values_list('receiver__userprofile', flat=True)
        current_user_sent_request_username = FriendRequest.objects.filter(sender=cur_user).values_list('receiver__userprofile__user__username', flat=True)
        print current_user_sent_request_username
        friend_request = FriendRequest.objects.get(receiver=request.user)
        print 'friend request', friend_request
        cur_user_incoming_request_list = friend_request.sender.exclude(user=request.user)
        print '525', cur_user_incoming_request_list
        #print friend_request
        if request.user.is_staff or request.user.is_superuser:
            queryset_list = UserProfile.objects.exclude(user=request.user.id)
    
        query = request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(user__username__icontains=query)|
                Q(user__first_name__icontains=query)|
                Q(user__last_name__icontains=query)|
                Q(city__icontains=query)|
                Q(phone__icontains=query)
                ).distinct()
        paginator = Paginator(queryset_list, 10) # Show 10 records per page
        page_request_var = "page"
        page = request.GET.get(page_request_var)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)
        context = {
            "object_list" : queryset,
            "title" : "Aptence User List",
            "page_request_var" : page_request_var,
            "friends" : friend,
            "my_sent_request" : current_user_sent_request,
            "my_sent_request_username" : current_user_sent_request_username,
            "incoming_request" : cur_user_incoming_request_list,
        }

        return render(request, "users_list.html" ,context)

def leaderboard(request):
    rank_obj = Rank(request.user)
    #users = UserProfile.objects.all().order_by('coin')
    user = Friend.objects.get(current_user=request.user)
    lbusers_list = user.friends.all().order_by('-coin')
    print lbusers_list
    context = {
        'rank_obj': rank_obj.rank(),
        'lbusers_list': lbusers_list,
    }

    return render(request, 'leaderboard.html', context)

def friend_request(request, pk):
    #sender_obj = FriendRequest.objects.get_or_create(sender=request.user)
    friend = UserProfile.objects.get(pk=pk)
    sender_obj = UserProfile.objects.get(user=request.user)
    print friend
    #print request.user
    receiver_obj = FriendRequest.objects.get_or_create(receiver=friend.user)
    receiver_obj[0].sender.add(sender_obj) 
    #receiver_obj.receiver= friend.user.username
    receiver_obj[0].save()
    friend.notification = "You received a friend request"
    friend.save()
    print receiver_obj
    print friend
    return redirect('home:list')
    
def notification(request):
    user = FriendRequest.objects.get(receiver=request.user)
    lbusers_list = user.sender.all()
    context = {
        'currentuser': user,
        'lbusers_list': lbusers_list,
    }

    return render(request, 'notification.html', context)

def resolve_request(request, operation, pk):
    friend = UserProfile.objects.get(pk=pk)
    receiver_obj = FriendRequest.objects.get(receiver= request.user)
    if operation == "accept":
        #add sender in receivers friend list
        friend_cls_obj = Friend.objects.get(current_user=request.user)
        friend_cls_obj.make_friend(friend)
        #add receiver in senders friend list
        sender = UserProfile.objects.get(user= request.user)
        sender_obj = Friend.objects.get(current_user= friend.user)
        sender_obj.make_friend(sender)
        receiver_obj.sender.remove(friend)
    elif operation == "reject":
        receiver_obj.sender.remove(friend)
    return redirect('home:notification')

def change_group_name(request):
    friend_cls_obj = Friend.objects.get(current_user=request.user)
    grpname = request.POST['grpname']
    print grpname
    friend_cls_obj.group_name = grpname
    friend_cls_obj.save()
    return redirect('home:home')

friend_group/src/home/templates/home.html
{% extends "landing_header_friend.html" %}
{% load static %}

{% block  extra_css %}
<style>

.goog-trans-control { 
  float: left;
  border: groove 1px gray; background: #ddd;
  border-radius: 3px;
  padding: 0 0.3em; }
.send {
  clear: both;
  margin-top: 2em; }
.goog-trans-control { 
  margin-right: 1em; }
.goog-trans-control * {
  color: black;
  text-decoration: none;
  font: 100% Calibri, sans-serif !important; }
#text {
  min-height: 4em;
  border: solid 1px; }
</style>
<script src="{% static 'js/annyang.min.js' %}"></script>
<script src="{% static 'js/voice.js' %}"></script>

<script type="text/javascript">
    var checkpronun2 = function() {
    var word = document.getElementById("wordcheck").value;
    
    var u = new SpeechSynthesisUtterance(); 
    //var user = document.getElementById('wordcheck').value;
     u.text = word;
     u.lang = 'en-US';
     u.rate = 1.0;
     speechSynthesis.speak(u); 
     document.getElementById("result").innerHTML = "<b>You checked pronunciation for:</b> " + word; 
    };
  

</script>

{% endblock %}

{% block content %}
<br><br>
<div class="container friend">

   
    <div class="col-md-9">
    
        
         <h2 style="color: royalblue;">{{ frndobj.group_name }}</h2>
        
        <form method="post" id="postform">
            {% csrf_token %}
            {{ form.post }}
            <br>
            <button type="submit">Submit</button>
        </form>
        <h2>{{ text }}</h2>
        {% for post in posts %}
        {% if post.user == request.user and post.user.get_full_name %}
          <h1 style="border-style: outset; text-align: right;">
            <p style="font-size: 15px; text-align: center;">{{ post.created }}</p>
            <i style="font-size: 15px;"><b>&nbsp;{{ post.user.get_full_name }}(You) </b></i>
        {% elif post.user == request.user %}
          <h1 style="border-style: outset; text-align: right;">
            <p style="font-size: 15px; text-align: center;">{{ post.created }}</p>
            <i style="font-size: 15px;"><b>&nbsp;You </b></i>
        {% elif post.user.get_full_name %}
          <h1 style="border-style: outset;">
            <p style="font-size: 15px; text-align: center;">{{ post.created }}</p>
            <i style="font-size: 15px;"><b>&nbsp;{{ post.user.get_full_name }} </b></i>
        {% elif post.user.get_first_name %}
          <h1 style="border-style: outset;">
            <p style="font-size: 15px; text-align: center;">{{ post.created }}</p>
            <i style="font-size: 15px;"><b>&nbsp;{{ post.user.get_first_name }} </b></i>
        {% else %}
          <h1 style="border-style: outset;">
            <p style="font-size: 15px; text-align: center;">{{ post.created }}</p>
            <i style="font-size: 15px;"><b>&nbsp;{{ post.user }} </b></i>
        {% endif %}
        {% if post.user == request.user %}
          <p style="font-size: 18px; text-align: right;">{{ post.post }}</p>
        {% else %}
          <p style="font-size: 18px; text-align: left;">{{ post.post }}</p>
        {% endif %}
              
            </h1>
            <!-- Posted by {{ post.user.get_full_name }} on {{ post.created }} -->
        {% endfor %}
        <center>
            <div class="pagination">
           
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?{{ page_request_var }}={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Newer</a>
                {% endif %}
        
                <span class="current">
                    Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                </span>
        
                {% if posts.has_next %}
                    <a href="?{{ page_request_var }}={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Older</a>
                {% endif %}
            </span> 
        
        </div> </center>
         </div>
         <div class="col-md-3">
         <b><span style="color:#32c5d2;">{{ frndobj.group_name }}</span></b>
         <form method="POST" action="{% url 'home:change_group_name' %}">
         {% csrf_token %}
         <input class="" type="text" name="grpname" id="grname" maxlength="20" placeholder="Desired Group Name" required>
         <input type="submit" id="grpsubmit" value="Change" class="btn btn-info">
         </form><br>
        <b>Friends</b><br>

        {% for friend in friends %}
            <table class="table table-striped">
         <tr>
         <td> <a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}">
            {% if friend.user.get_full_name %}
                {{ friend.user.get_full_name }}
            {% elif friend.user.get_first_name %}
            {{ friend.user.get_first_name }}
            {% else %}
            {{ friend.user }}
            {% endif %}
            </a></td>
            <td>
            <a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}" class="pull-right">
            <button type="button" class="btn btn-default btn-sm" id="removefrnd">Remove Friend</button>
            </a></td></tr></table>
        {% endfor %}
    </div>
    </div>
    
<script>
function googleSectionalElementInit() {
  new google.translate.SectionalElement({
    sectionalNodeClassName: 'goog-trans-section',
    controlNodeClassName: 'goog-trans-control',
    background: '#f4fa58'
  }, 'google_sectional_element');
}
</script>

 
{% endblock %}
{% block footer %}
     
{% endblock %}

friend_group/src/home/templates/landing_header_friend.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-83590998-1', 'auto');
  ga('send', 'pageview'); 
</script>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'images/Aptence logo.png' %}">
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="google-site-verification" content="QFT2cJyPAsdiBK8VapRPiGWBwkpb_N5Zceyi3ONRuhs" />
    <!-- Google fonts -->
<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
<!--- font awesome -->
    

<script src="{% static 'js/agency.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'assets/plugins/jquery.min.js' %}" type="text/javascript"></script>  
 <script src="{% static 'assets/plugins/jquery-migrate.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>


    {% block title %}
    <title>Friend Group Web app by Mohit</title>
    {% endblock %}
 
  
    {% block css %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/agency.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <script type="text/javascript">
    var logoutclick = function() {
        var u = new SpeechSynthesisUtterance(); 
        var user = document.getElementById('usrnm').value;
       u.text = "GoodBye!" + user + ' see you soon';
       u.lang = 'hi-IN';
       u.rate = 1.0;
       speechSynthesis.speak(u);
       setTimeout(function(){
          window.location.href = '/users/logout';
       }, 2000) 
    };
    </script>

   
    {% endblock %}

    {% block extra_css %}

 <style type="text/css">
    html
    {
        max-width: 100%;
    }
    body
    {
    max-width: 100%;
    overflow-x: hidden;
    }
               .c-content-box.c-size-md{
                    background-color: #F0F0F0;
                }
                .tp-bullets.round > .tp-bullet.selected{
                    background-color: #e1e8e9;
                }
                #reg_form1 .form-control{
                    font-size: 12px !important;
                    height: 37px !important;

                }
                #reg_form1 .c-theme-btn.btn{
                    height: 38px;
                    line-height: 20px;
                }
                #reg_form1 .c-btn-uppercase.btn-md{
                    font-size: 14px;
                }
                #extra_links ul{
                    width: 100%;
                }
                .loader {
                    position: fixed;
                    left: 0px;
                    top: 0px;
                    width: 100%;
                    height: 100%;
                    z-index: 9999;
                    background: url('{% static 'gif/Preloader_2.gif' %}') 50% 50% no-repeat rgb(249,249,249);
                }
p,a,h5{
color:#7f8c97 ;
}

.c-content-title-1.c-title-md > h3.c-font-uppercase{
color:#bbb !important;
}
.c-prefooter.c-bg-white
{
background:#000 !important;
}
@media (min-width:1023px) and (max-width: 1026px){
footer{
    bottom: 0;
    left: 0;
    width: 100%; 
}}

@media (max-width: 440px)
{
.input-group-lg > .form-control, .input-group-lg > .input-group-addon, .input-group-lg >
.input-group-btn > .btn
{
padding: 5px;
font-size: 12px;
}
.dropdown-menu{
    right:0 !important;
}
}
            </style>


    {% endblock %}
</head> 

{% block header %}

<body id="page-top" class="index">

    <!-- Navigation -->
    
    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top friend">
        <div class="container menu"> 
            
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only"></span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'home:home' %}"><img src="{% static 'img/logos/logo3.jpeg' %}" height= 70px width= 70px></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right friend">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'home:home'%}">home</a>
                    </li>
                    
                    <li>
                        <a class="page-scroll" href="{% url 'home:list' %}"> Friend &nbsp; <i class="fa fa-search" aria-hidden="true"></i></a>
                    </li> 
                     <li>
                        <a class="page-scroll" href="{% url 'home:leaderboard' %}"><i class="fa fa-users" aria-hidden="true"></i> &nbsp;Leaderboard  </a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'home:notification' %}"><i class="fa fa-bell" aria-hidden="true"></i> Notification</a>
                    </li>
                    {% if user.is_authenticated %}
					<input type="hidden" id="usrnm" value="{{user.username}}"></input>
                    <li><a class="page-scroll" href="{% url 'accounts:view_profile' %}">Welcome {{ user.username }}</a></li>
                    <li><a class="page-scroll" href="{% url 'accounts:logout' %}" onclick="logoutclick()">Logout</a></li>
                    {% else %}
                    <li>
                        <a class="page-scroll" href="{% url 'accounts:login' %}"><i class="fa fa-bell" aria-hidden="true"></i> Login</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'accounts:register' %}"><i class="fa fa-bell" aria-hidden="true"></i> Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        
    </nav>
 
    


{% endblock %}
{% block content %}
{% endblock %}

{% block footer %}
   
{% endblock %}

friend_group/src/home/templates/leaderboard.html
{% extends "landing_header_friend.html" %}
{% load static %}

{% block  extra_css %}
<script src="{% static 'js/annyang.min.js' %}"></script>
<script src="{% static 'js/voice.js' %}"></script>
<script type="text/javascript">
     var u = new SpeechSynthesisUtterance();
     u.text = 'Hello {{user.get_full_name}}! {{lbusers_list.0}} is topping the Leaderboard';
     u.lang = 'hi-IN';
     u.rate = 1.0;
     //u.onend = function(event) { alert('Finished in ' + event.elapsedTime + ' seconds.'); }
     speechSynthesis.speak(u);
     
     //speechSynthesis.cancel();
</script>

{% endblock %}

{% block content %}
<br><br>
<div class="container friend"> 
<center><h4 style="color:#32c5d2;">Leader Board</h4></center>
<br>
{% for user in lbusers_list %}
 <!-- { % url "posts:detail" id=obj.id % } -->   
  <div class="row"> 
  <div class="col-sm-12">
   <div class="thumbnail">
       
      <!--<a href=""> -->
              <div class="table-responsive">   
             <table class="table table-striped">
                  <tr>
                  <th></th>
                  <th> Rank</th>
                  <th id="name">Name </th>
                 <th>Username </th>
                 <th> Score</th>
                   </tr> 
                  <tr>
                  <td>
                 {% if user.image %}
                 <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                                            
      <img src="/media/{{user.image}}" class="img-responsive" style="width:80px;height:50px;"></a>
      {% else %}
       <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
      <img  src="/media/image_not_available.png" class="img-responsive  profilleimage" style="width:80px;height:50px;"></a>
      {% endif %}
                   </td>
                   <td> #{{ forloop.counter }} </td>
                   <td> {{user.user.get_full_name}} </td>
                    <td>{{user}}</td>
                    <td> {{user.coin}} </td>
                  </tr>
                     </table>
      </div>          
    </div>
  </div>
  </div> 

    {% endfor %}

</div> 
{% endblock %}

friend_group/src/home/templates/notification.html
{% extends "landing_header_friend.html" %}
{% load static %}

{% block  extra_css %}
<script src="{% static 'js/annyang.min.js' %}"></script>
<script src="{% static 'js/voice.js' %}"></script>

{% endblock %}

{% block content %}
<br><br>
<div class="container friend">
{% if not lbusers_list %}
<center><h4 style="color:#ac2925;">You have no incoming friend request.</h4></center>
<script type="text/javascript">
     var u = new SpeechSynthesisUtterance();
     u.text = 'Hello {{user.get_full_name}}! Looks like no one have requested you, come and check sometime later';
     u.lang = 'hi-IN';
     u.rate = 1.0;
     //u.onend = function(event) { alert('Finished in ' + event.elapsedTime + ' seconds.'); }
     speechSynthesis.speak(u);
     
     //speechSynthesis.cancel();
</script>
{% else %}
<center><h4 style="color:#32c5d2;">You have following friend request(s)</h4></center>
<script type="text/javascript">
     var u = new SpeechSynthesisUtterance();
     u.text = 'Hello {{user.get_full_name}}! You have following friend requests';
     u.lang = 'hi-IN';
     u.rate = 1.0;
     speechSynthesis.speak(u);
</script>
{% endif %}

{% for user in lbusers_list %}

<div class="row">
  <div class="col-sm-12">

    <div class="thumbnail">
      <center> <span style="color:#222;font-size:20px;">#{{ forloop.counter }} </span><br>
      {% if user.image %} 
      &nbsp;&nbsp;<img src="/media/{{user.image}}" style="width:100px;height:80px">
      {% else %}
           &nbsp; &nbsp;<img  src="/media/image_not_available.png" class="img-responsive  profilleimage" style="width:100px;height:80px">
      {% endif %}
      <!-- <a href=""> -->
              <div class="table-responsive">
                    <table class="table table-striped" style="margin-top: 20px;">
                 <tr> <th>Name</th> 
                  <th>Username</th> 
                                       <th> Score</th>
                                       <th></th>
                                       <th></th>
                                        </tr> 
                                                <tr>
                                           <td><a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                                            {{user.user.get_full_name}} </a>
                                                </td>
                                                  <td>
                                              {{user}}
                                                  </td>
            
                                                        <td>
                                                {{user.coin}}
                                                        </td>
                                                        
                                       <td>
                                        <a id="accept" href="{% url 'home:resolve_request' operation='accept' pk=user.pk %}" class="btn btn-success">
                                Accept</a></td>
                                <td>
                                <a id="reject" href="{% url 'home:resolve_request' operation='reject' pk=user.pk %}" class="btn btn-danger">
                                Reject </a>
                                  </td>
                                </tr>
</table> </div> 
    </div>
  </div>
 
  </div>
  {% endfor %}
</div>
{% endblock %}