friend_group/src/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete,
)


urlpatterns = [
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')
    
]

friend_group/src/aptfrnd/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from aptfrnd import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),
] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friend_group/src/home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views
from .views import users_list, leaderboard, friend_request, notification, resolve_request, change_group_name

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends'),
    url(r'^searchusers/$', users_list, name='list'),
    url(r'^leaderboard/$', leaderboard, name='leaderboard'),
    url(r'^request/(?P<pk>\d+)/$', friend_request, name='send_request'),
    url(r'^resolverequest/(?P<operation>.+)/(?P<pk>\d+)/$', resolve_request, name='resolve_request'),
    url(r'^notification/$', notification, name='notification'),
    url(r'^change_group_name/$', change_group_name, name='change_group_name'),
]

friend_group/src/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

#class UserProfileManager(models.Manager):
 #   def get_queryset(self):
  #      return super(UserProfileManager, self).get_queryset().filter(city='Delhi')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=200, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)
    coin = models.IntegerField(default='500')
    rank = models.IntegerField(default='0')
    notification = models.CharField(max_length=400, default="" )

    #India = UserProfileManager()

    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'

    def __str__(self):
        return self.user.username

#def create_profile(sender, **kwargs):
 #   if kwargs['created']:
  #      user_profile = UserProfile.objects.create(user=kwargs['instance'])

#post_save.connect(create_profile, sender=User)

friend_group/src/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )
        

class EditPersonalDetailsForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = (
            'description',
            'phone',
            'city',
            'website'
        )
        

friend_group/src/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
    EditPersonalDetailsForm
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from urllib import quote_plus
from home.models import Friend, FriendRequest
from .models import UserProfile


def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # friend_cls_obj = Friend.objects.create(current_user=user)
            #userpro = UserProfile.objects.create(user=user)
            #friend_cls_obj.friends.add(userpro)
            # FriendRequest.objects.create(receiver=user)
            return redirect(reverse('accounts:login'))
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

def view_profile(request, pk=None):
    if pk:
        user = UserProfile.objects.get(pk=pk)
    else:
        user = request.user.userprofile
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        form1 = EditPersonalDetailsForm(request.POST or None, request.FILES or None, instance=request.user.userprofile)
        ds = request.POST['description']
        ct = request.POST['city']
        ws = request.POST['website']
        ph = request.POST['phone']
        print(ds, ph, ct, ws)
        if form.is_valid() and form1.is_valid():
            form.save()
            if request.POST['image'] is not '':
                request.user.userprofile.image = "profile_image/"+request.POST['image']
                print("bb",request.POST['image'])
                request.user.userprofile.save()
            else:
                print("aa",request.user.userprofile.image.url)
            form1.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        form1 = EditPersonalDetailsForm(instance=request.user.userprofile)
        args = {'form': form, 'form1': form1,}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

friend_group/src/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

friend_group/src/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form1.as_p }}
        <p><label for="id_image">Image:</label> <br>
            Currently: <a href= "{{ request.user.userprofile.image.url }}" >{{ request.user.userprofile.image.url }}</a>
            <input type ='file' name='image' id="id_image" value="{{ request.user.userprofile.image.url }}" /></p>
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

friend_group/src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can log in here!
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

friend_group/src/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

friend_group/src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    {% if user.image %}
    <img src="/media/{{user.image}}" alt="Me" height="100" width="100">
    {% endif %}
    <p>Username: {{ user.user }}</p>
    <p>First name: {{ user.user.first_name }}</p>
    <p>Last name: {{ user.user.last_name }}</p>
    <p>Email: {{ user.user.email }}</p>
    <p>Description: {{ user.description }}</p>
    <p>Phone: {{ user.phone }}</p>
    <p>City: {{ user.city }}</p>
    <p>Website: {{ user.website }}</p>
    <p>Coins: {{ user.coin }}</p>
    
    
   
</div>

{% endblock %}

friend_group/src/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

friend_group/src/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

friend_group/src/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

friend_group/src/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

friend_group/src/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

friend_group/src/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

friend_group/src/accounts/templates/accounts/users_list.html
{% extends "base.html" %}
{% block body %}
    
    <div class='col-sm-6 col-sm-offset-3'>
      <h1>{{title}}</h1>
    <form method='GET' action=''>
    <input type='text' name='q' placeholder='Search posts' value='{{request.GET.q}}' />
    <input type='submit' value='Search' />
    </form>
    
    {% for obj in object_list %}
   
  <!-- { % url "posts:detail" id=obj.id % } -->
  <div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
      {% if obj.image %}
      <img src="{{obj.image.url}}" alt="..."> 
      {% endif %}
      <div class="caption">
        <h3><a href='{{ obj.get_absolute_url }}'>{{obj.user}}</a><small> {{obj.city}} </small></h3>
        {% if obj.user.get_full_name %}<p>User: {{ obj.user.get_full_name }}</p>{% endif %}
        <p>{{obj.description|linebreaks|truncatechars:120}}</p>
        <p>{{obj.coin}}</p>
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View User</a></p>
      </div>
    </div>
  </div>
  <hr/>
  </div>

    {% endfor %}
    
    <div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
  
  </div>
    {% endblock body %}
</div>